// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSchedule struct {
	Title  string `json:"title"`
	UserID string `json:"userId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Schedule struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	User  *User  `json:"user"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Todos    []*Todo     `json:"todos"`
	Schedule []*Schedule `json:"schedule"`
}
